import type { IntegrationProvider } from './IntegrationCard';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';

export const PROVIDERS: IntegrationProvider[] = [
  // CRM
  {
    id: 'close_crm',
    name: 'Close CRM',
    category: 'CRM',
    iconLetter: 'C',
    iconBg: 'hsl(221 83% 53%)',
    description: 'Deals und Kontakte synchronisieren',
    fields: [
      { key: 'webhook_url', label: 'n8n Webhook URL', type: 'text', placeholder: 'https://n8n...' },
      { key: 'api_key', label: 'Close API Key', type: 'password', placeholder: 'api_key_...' },
    ],
    toggles: [{ key: 'auto_sync', label: 'Auto-Sync (alle 15 Min.)' }],
    webhookUrl: `${SUPABASE_URL}/functions/v1/webhook-receiver/close`,
    docUrl: 'https://developer.close.com/',
    actions: [
      { label: 'Synchronisieren', variant: 'outline', action: 'sync' },
      { label: 'Speichern', action: 'save' },
    ],
    ariaGuide: [
      'Öffne Close CRM → Einstellungen → API',
      'Erstelle einen neuen API Key mit Lese-/Schreibrechten',
      'Kopiere den Key und trage ihn oben ein',
      'Optional: n8n Webhook URL für bidirektionale Synchronisation',
      'Klicke "Speichern" um die Verbindung herzustellen',
    ],
    healthChecks: [
      { id: 'api_reachable', label: 'API erreichbar' },
      { id: 'auth_valid', label: 'Authentifizierung gültig' },
      { id: 'leads_readable', label: 'Leads lesbar' },
      { id: 'deals_readable', label: 'Deals lesbar' },
      { id: 'activities_writable', label: 'Aktivitäten schreibbar' },
    ],
  },
  // Marketing
  {
    id: 'meta_ads',
    name: 'Meta Ads',
    category: 'Marketing',
    iconLetter: 'f',
    iconBg: 'linear-gradient(135deg, hsl(221 83% 53%), hsl(221 83% 40%))',
    description: 'Ad Accounts und Kampagnen verwalten',
    fields: [
      { key: 'access_token', label: 'Access Token', type: 'password', placeholder: 'EAABsbCS...' },
      { key: 'business_manager_id', label: 'Business Manager ID', type: 'text', placeholder: '148696358323685' },
    ],
    docUrl: 'https://developers.facebook.com/docs/marketing-apis',
    actions: [
      { label: 'Verbinden', action: 'save' },
    ],
    hasAccountMapping: true,
    ariaGuide: [
      'Gehe zu business.facebook.com',
      'Einstellungen → Sicherheit → API-Zugriffstoken',
      'Erstelle ein System-User Token mit: ads_read, ads_management, business_management',
      'Business Manager ID: Einstellungen → Unternehmensinfo',
      'Nach dem Verbinden: Kundenkonten zuordnen',
    ],
    healthChecks: [
      { id: 'token_valid', label: 'Access Token gültig' },
      { id: 'business_reachable', label: 'Business Manager erreichbar' },
      { id: 'accounts_readable', label: 'Ad Accounts lesbar' },
      { id: 'campaigns_readable', label: 'Kampagnendaten lesbar' },
      { id: 'spend_readable', label: 'Ausgaben-Daten lesbar' },
      { id: 'insights_api', label: 'Insights API erreichbar' },
    ],
  },
  {
    id: 'google_ads',
    name: 'Google Ads',
    category: 'Marketing',
    iconLetter: 'G',
    iconBg: 'hsl(0 0% 100%)',
    iconColor: 'hsl(221 83% 53%)',
    description: 'Google Ads Kampagnen',
    comingSoon: true,
    fields: [],
    actions: [],
    ariaGuide: [],
    healthChecks: [],
  },
  // Kommunikation
  {
    id: 'slack',
    name: 'Slack',
    category: 'Kommunikation',
    iconLetter: '#',
    iconBg: 'hsl(271 76% 53%)',
    description: 'Benachrichtigungen und Automatisierungen',
    fields: [
      { key: 'bot_token', label: 'Bot Token (xoxb-...)', type: 'password', placeholder: 'xoxb-...' },
    ],
    toggles: [],
    webhookUrl: `${SUPABASE_URL}/functions/v1/webhook-receiver/slack`,
    actions: [
      { label: 'Test senden', variant: 'outline', action: 'test' },
      { label: 'Speichern', action: 'save' },
    ],
    ariaGuide: [
      'Gehe zu api.slack.com/apps und erstelle eine neue App',
      'Unter "OAuth & Permissions": Bot Token Scopes hinzufügen (chat:write, channels:read)',
      'App im Workspace installieren → Bot Token kopieren',
      'Für Webhooks: Slack → Apps → Incoming WebHooks → Channel auswählen',
      'Tech Support Webhook in das entsprechende Feld eintragen',
    ],
    healthChecks: [
      { id: 'bot_token_valid', label: 'Bot Token gültig' },
      { id: 'workspace_reachable', label: 'Workspace erreichbar' },
      { id: 'webhook_active', label: 'Tech Support Webhook aktiv' },
      { id: 'channels_readable', label: 'Channels lesbar' },
      { id: 'messages_sendable', label: 'Nachrichten sendbar' },
    ],
  },
  {
    id: 'email',
    name: 'E-Mail (Gmail / IMAP)',
    category: 'Kommunikation',
    iconLetter: '✉',
    iconBg: 'hsl(4 90% 58%)',
    description: 'E-Mail Postfächer synchronisieren',
    fields: [
      { key: 'imap_host', label: 'IMAP Host', type: 'text', placeholder: 'imap.gmail.com' },
      { key: 'imap_port', label: 'Port', type: 'text', placeholder: '993' },
      { key: 'imap_user', label: 'Benutzername', type: 'text', placeholder: 'user@example.com' },
      { key: 'imap_pass', label: 'Passwort / App-Passwort', type: 'password' },
    ],
    actions: [
      { label: 'Testen', variant: 'outline', action: 'test' },
      { label: 'Verbinden', action: 'save' },
    ],
    ariaGuide: [
      'Für Gmail: Google Konto → Sicherheit → 2FA aktivieren',
      'Dann: App-Passwörter → neues App-Passwort für "Mail" erstellen',
      'IMAP Host: imap.gmail.com, Port: 993',
      'Benutzername: deine volle Gmail-Adresse',
      'App-Passwort (16 Zeichen) als Passwort verwenden',
    ],
    healthChecks: [
      { id: 'imap_connection', label: 'IMAP Verbindung' },
      { id: 'auth_valid', label: 'Authentifizierung' },
      { id: 'inbox_readable', label: 'Posteingang lesbar' },
    ],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    category: 'Kommunikation',
    iconLetter: 'W',
    iconBg: 'hsl(142 70% 49%)',
    description: 'WhatsApp Business API',
    comingSoon: true,
    fields: [],
    actions: [],
    ariaGuide: [],
    healthChecks: [],
  },
  // Finanzen
  {
    id: 'qonto',
    name: 'Qonto',
    category: 'Finanzen',
    iconLetter: 'Q',
    iconBg: 'hsl(var(--color-teal))',
    description: 'Banking & Transaktionen',
    fields: [
      { key: 'org_slug', label: 'Kennung (Login)', type: 'text', placeholder: 'viral-connect-gmbh-8234' },
      { key: 'api_key', label: 'Geheimschlüssel', type: 'password', placeholder: 'Dein Qonto Geheimschlüssel' },
    ],
    toggles: [{ key: 'auto_sync', label: 'Automatisch synchronisieren' }],
    docUrl: 'https://api-doc.qonto.com/',
    actions: [
      { label: 'Jetzt synchronisieren', variant: 'outline', action: 'sync' },
      { label: 'Verbinden', action: 'save' },
    ],
    ariaGuide: [
      'Öffne Qonto → Einstellungen → Integrationen → API',
      'Klicke auf "Neuen API-Schlüssel erstellen"',
      'Organisation Slug: findest du in der URL (z.B. haush-haush-digital)',
      'API Key kopieren und hier eintragen',
      'Auto-Sync aktivieren für regelmäßige Aktualisierung',
    ],
    healthChecks: [
      { id: 'api_valid', label: 'API Key gültig' },
      { id: 'org_found', label: 'Organisation gefunden' },
      { id: 'balance_readable', label: 'Kontostand lesbar' },
      { id: 'transactions_readable', label: 'Transaktionen lesbar' },
      { id: 'webhooks_configurable', label: 'Webhooks konfigurierbar' },
    ],
  },
  {
    id: 'datev',
    name: 'DATEV',
    category: 'Finanzen',
    iconLetter: 'D',
    iconBg: 'hsl(25 95% 53%)',
    description: 'Buchhaltung & Steuern',
    comingSoon: true,
    fields: [],
    actions: [],
    ariaGuide: [],
    healthChecks: [],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Finanzen',
    iconLetter: 'S',
    iconBg: 'hsl(271 76% 53%)',
    description: 'Zahlungsabwicklung',
    comingSoon: true,
    fields: [],
    actions: [],
    ariaGuide: [],
    healthChecks: [],
  },
  // Automatisierung
  {
    id: 'n8n',
    name: 'n8n',
    category: 'Automatisierung',
    iconLetter: '⚡',
    iconBg: 'hsl(25 95% 53%)',
    description: 'Workflow-Automatisierung',
    fields: [
      { key: 'instance_url', label: 'n8n Instance URL', type: 'text', placeholder: 'https://n8n.yourserver.com' },
      { key: 'api_key', label: 'API Key', type: 'password' },
      { key: 'webhook_base', label: 'Webhook Base URL', type: 'text', placeholder: 'https://...' },
    ],
    webhookUrl: `${SUPABASE_URL}/functions/v1/webhook-receiver/n8n`,
    docUrl: 'https://docs.n8n.io/',
    actions: [
      { label: 'Verbindung testen', variant: 'outline', action: 'test' },
      { label: 'Speichern', action: 'save' },
    ],
    ariaGuide: [
      'n8n Instanz URL: Die URL deiner gehosteten n8n Instanz',
      'Einstellungen → API → Neuen API Key erstellen',
      'API Key hier eintragen',
      'Webhook Base URL: Basis-URL für eingehende Webhooks',
      'Tipp: Nutze den Agency Hub Webhook-Endpoint für eingehende Daten',
    ],
    healthChecks: [
      { id: 'n8n_reachable', label: 'n8n erreichbar' },
      { id: 'api_valid', label: 'API Key gültig' },
      { id: 'workflows_readable', label: 'Workflows lesbar' },
      { id: 'webhook_reachable', label: 'Webhook URL erreichbar' },
    ],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'Automatisierung',
    iconLetter: 'Z',
    iconBg: 'hsl(16 90% 50%)',
    description: 'Verwende unsere API um Zaps zu erstellen',
    fields: [
      { key: 'webhook_url', label: 'Zapier Webhook URL', type: 'text', placeholder: 'https://hooks.zapier.com/...' },
    ],
    docUrl: 'https://zapier.com/developer',
    actions: [{ label: 'Speichern', action: 'save' }],
    ariaGuide: [
      'Erstelle einen neuen Zap in Zapier',
      'Wähle "Webhooks by Zapier" als Trigger',
      'Kopiere die Webhook URL und trage sie hier ein',
      'Konfiguriere die gewünschten Actions in Zapier',
    ],
    healthChecks: [
      { id: 'webhook_reachable', label: 'Webhook URL erreichbar' },
    ],
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    category: 'Automatisierung',
    iconLetter: 'M',
    iconBg: 'hsl(271 81% 40%)',
    description: 'Visual Automation Platform',
    fields: [
      { key: 'webhook_url', label: 'Make Webhook URL', type: 'text', placeholder: 'https://hook.eu1.make.com/...' },
    ],
    docUrl: 'https://www.make.com/en/api-documentation',
    actions: [{ label: 'Speichern', action: 'save' }],
    ariaGuide: [
      'Erstelle ein neues Scenario in Make',
      'Füge ein "Webhooks" Modul als Trigger hinzu',
      'Kopiere die generierte Webhook URL',
      'Hier eintragen und "Speichern" klicken',
    ],
    healthChecks: [
      { id: 'webhook_reachable', label: 'Webhook URL erreichbar' },
    ],
  },
  // Storage
  {
    id: 'google_drive',
    name: 'Google Drive',
    category: 'Storage',
    iconLetter: '📁',
    iconBg: 'hsl(45 93% 47%)',
    description: 'Dokumente & Dateien',
    fields: [
      { key: 'root_folder_id', label: 'Root-Ordner ID', type: 'text', placeholder: '1abc...' },
    ],
    docUrl: 'https://developers.google.com/drive',
    actions: [
      { label: 'Ordnerstruktur aufbauen', variant: 'outline', action: 'build_structure' },
      { label: 'Verbinden', action: 'connect' },
    ],
    ariaGuide: [
      'Google Drive öffnen und einen Root-Ordner für das Agency Hub erstellen',
      'Ordner-ID: In der URL nach /folders/ → die ID kopieren',
      'OAuth: "Mit Google verbinden" klicken und Zugriff gewähren',
      'Ordner-Mappings: Kunden-Dokumente, Rechnungen, Akademie zuordnen',
    ],
    healthChecks: [
      { id: 'oauth_valid', label: 'OAuth Token gültig' },
      { id: 'drive_reachable', label: 'Drive erreichbar' },
      { id: 'files_readable', label: 'Dateien lesbar' },
      { id: 'upload_possible', label: 'Hochladen möglich' },
    ],
  },
  // Landing Pages
  {
    id: 'onepage',
    name: 'OnePage.io',
    category: 'Landing Pages',
    iconLetter: 'O',
    iconBg: 'hsl(271 76% 53%)',
    description: 'Landing Pages & Formulare',
    fields: [
      { key: 'api_key', label: 'API Key', type: 'password', placeholder: 'op_key_...' },
    ],
    docUrl: 'https://app.onepage.io',
    actions: [
      { label: 'Verbindung testen', variant: 'outline', action: 'test' },
      { label: 'Speichern', action: 'save' },
    ],
    ariaGuide: [
      'Öffne OnePage.io → Einstellungen → API',
      'Neuen API Key erstellen',
      'Key kopieren und hier eintragen',
      'Klicke "Verbindung testen" um zu prüfen',
    ],
    healthChecks: [
      { id: 'api_valid', label: 'API Key gültig' },
      { id: 'contacts_readable', label: 'Kontakte lesbar' },
      { id: 'pipeline_readable', label: 'Pipeline lesbar' },
    ],
  },
  {
    id: 'superchat',
    name: 'Superchat',
    category: 'CRM/Chat',
    iconLetter: '💬',
    iconBg: 'hsl(var(--color-teal))',
    description: 'Kundenkommunikation',
    comingSoon: true,
    fields: [],
    actions: [],
    ariaGuide: [],
    healthChecks: [],
  },
];

export const CATEGORIES = [
  'Alle', 'Verbunden', 'Nicht verbunden', 'CRM', 'Marketing', 'Finanzen', 'Kommunikation', 'Automatisierung', 'Storage', 'Landing Pages',
];
